# Generated by Django 5.1.4 on 2026-03-26 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_add_birth_place_nationality'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_value', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('type_evaluation', models.CharField(choices=[('DEVOIR', 'Devoir'), ('EXAMEN', 'Examen'), ('ORAL', 'Oral'), ('TP', 'Travaux Pratiques'), ('COMPOSITION', 'Composition')], default='DEVOIR', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='subjects.subject')),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['-date', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('subject_name', models.CharField(max_length=100)),
                ('change_type', models.CharField(choices=[('CREATED', 'Créée'), ('UPDATED', 'Modifiée'), ('DELETED', 'Supprimée')], max_length=10)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='grades.grade')),
            ],
            options={
                'db_table': 'grade_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
