# Generated by Django 5.1.4 on 2026-07-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_type_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='period',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
