# Generated by Django 5.1.4 on 2026-07-09 00:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=64, unique=True)),
                ('plan', models.CharField(choices=[('TRIAL', 'Essai'), ('LICENSED', 'Sous licence')], default='TRIAL', max_length=10)),
                ('trial_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_code', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licence',
                'db_table': 'license',
            },
        ),
    ]
