# Generated by Django 5.1.4 on 2026-03-26 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(max_length=200)),
                ('objectives', models.TextField(blank=True, default='')),
                ('content_covered', models.TextField(blank=True, default='')),
                ('homework', models.TextField(blank=True, default='', verbose_name='Travail à la maison')),
                ('progression_percent', models.PositiveSmallIntegerField(default=0, help_text='Pourcentage du programme couvert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_logs', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_logs', to='teachers.teacher')),
            ],
            options={
                'db_table': 'lesson_logs',
                'ordering': ['-date', 'subject__name'],
            },
        ),
    ]
