# Generated by Django 5.1.4 on 2026-06-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('teachers', '0002_add_expense_and_lessonlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='classes.classe'),
        ),
    ]
