# Generated by Django 5.1.4 on 2026-07-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
