# Generated by Django 5.1.4 on 2026-03-26 07:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('GRADE_ADD', 'Note ajoutée'), ('GRADE_EDIT', 'Note modifiée'), ('GRADE_DELETE', 'Note supprimée'), ('PAYMENT_ADD', 'Paiement enregistré'), ('PAYMENT_EDIT', 'Paiement modifié'), ('STUDENT_ADD', 'Élève ajouté'), ('STUDENT_EDIT', 'Élève modifié'), ('USER_ADD', 'Utilisateur créé'), ('USER_EDIT', 'Utilisateur modifié'), ('PASSWORD_RESET', 'Mot de passe réinitialisé')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
