# Generated by Django 5.1.4 on 2026-06-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Professeur'), ('AGENT', "Agent d'accueil"), ('EDUCATEUR', 'Éducateur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DIRECTOR', 'Directeur'), ('TEACHER', 'Professeur'), ('AGENT', "Agent d'accueil"), ('EDUCATEUR', 'Éducateur')], default='TEACHER', max_length=20),
        ),
    ]
