# Generated by Django 5.1.4 on 2026-06-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_invitation_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Professeur'), ('AGENT', "Agent d'accueil"), ('EDUCATEUR', 'Éducateur'), ('CAISSE', 'Caisse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DIRECTOR', 'Directeur'), ('TEACHER', 'Professeur'), ('AGENT', "Agent d'accueil"), ('EDUCATEUR', 'Éducateur'), ('CAISSE', 'Caisse')], default='TEACHER', max_length=20),
        ),
    ]
