# Generated by Django 5.1.4 on 2026-06-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='new_value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='old_value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='os',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
