# Generated by Django 5.1.4 on 2026-07-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_backfill_ecole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('GRADE_ADD', 'Note ajoutée'), ('GRADE_EDIT', 'Note modifiée'), ('GRADE_DELETE', 'Note supprimée'), ('PAYMENT_ADD', 'Paiement enregistré'), ('PAYMENT_EDIT', 'Paiement modifié'), ('STUDENT_ADD', 'Élève ajouté'), ('STUDENT_EDIT', 'Élève modifié'), ('STUDENT_DELETE', 'Élève(s) supprimé(s)'), ('USER_ADD', 'Utilisateur créé'), ('USER_EDIT', 'Utilisateur modifié'), ('USER_DELETE', 'Utilisateur(s) supprimé(s)'), ('PASSWORD_RESET', 'Mot de passe réinitialisé')], max_length=30),
        ),
    ]
