# Generated by Django 5.1.4 on 2026-06-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
