# Generated by Django 5.1.4 on 2026-06-30 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classe_tuition_fee'),
        ('subjects', '0002_alter_subject_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, default='', max_length=100)),
                ('room', models.CharField(blank=True, default='', max_length=50)),
                ('day', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')], default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='classes.classe')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='subjects.subject')),
            ],
            options={
                'db_table': 'schedule_entries',
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
