# Generated by Django 5.1.4 on 2026-06-30 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_scheduleentry'),
        ('users', '0011_invitation_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.ecole'),
        ),
        migrations.AddField(
            model_name='classe',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.ecole'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
