# Generated by Django 5.1.4 on 2026-07-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_schedulefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionTranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='classes.classe')),
            ],
            options={
                'db_table': 'pension_tranches',
                'ordering': ['order', 'due_date', 'id'],
            },
        ),
    ]
