# Generated by Django 5.1.4 on 2026-03-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('matricule', models.CharField(blank=True, max_length=20, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('qr_code_data', models.CharField(blank=True, max_length=100, unique=True)),
                ('parent_name', models.CharField(blank=True, default='', max_length=200)),
                ('parent_phone', models.CharField(blank=True, default='', max_length=20)),
                ('parent_email', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('payment_status', models.CharField(choices=[('PAID', 'Payé'), ('PENDING', 'En attente'), ('OVERDUE', 'En retard')], default='PENDING', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.classe')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
