# Generated by Django 5.1.4 on 2026-03-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='idx_student_classe_active',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='idx_student_payment_status',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='idx_student_fullname',
        ),
    ]
