# Generated by Django 5.1.4 on 2026-03-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0004_remove_student_idx_student_classe_active_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['classe', 'is_active'], name='idx_student_classe_active'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['payment_status'], name='idx_student_payment_status'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name'], name='idx_student_fullname'),
        ),
    ]
