# Generated by Django 5.1.4 on 2026-06-30 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_idx_student_classe_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CERTIFICAT', 'Certificat'), ('ACTE_NAISSANCE', 'Acte de naissance'), ('PHOTO', 'Photo'), ('DIPLOME', 'Diplôme'), ('BULLETIN_SIGNE', 'Bulletin signé'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
