# Generated by Django 5.1.4 on 2026-07-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discount_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'Aucune'), ('PERCENT', 'Pourcentage'), ('FIXED', 'Montant fixe')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
