# Generated by Django 5.1.4 on 2026-06-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_documenttemplate_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='style_preset',
            field=models.CharField(choices=[('classic', 'Classique scolaire'), ('modern', 'Moderne'), ('minimalist', 'Minimaliste'), ('premium', 'Premium'), ('green', 'Nature'), ('warm', 'Chaleureux')], default='classic', max_length=20),
        ),
    ]
