# Generated by Django 5.1.4 on 2026-06-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_documenttemplate_style_preset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, default='', max_length=200)),
                ('school_year', models.CharField(blank=True, default='', max_length=20)),
                ('school_type', models.CharField(blank=True, default='all', max_length=20)),
                ('bulletin_header', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platform/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réglages plateforme',
                'verbose_name_plural': 'Réglages plateforme',
                'db_table': 'platform_settings',
            },
        ),
    ]
