# Generated by Django 5.1.4 on 2026-07-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_documenttemplate_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='ecole',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='platform_settings',
                to='users.ecole',
            ),
        ),
    ]
