# Generated by Django 5.1.4 on 2026-07-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_platformsettings_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='matricule_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='matricule_format',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='receipt_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='receipt_format',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
