# Generated by Django 5.1.4 on 2026-07-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_platformsettings_matricule_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='decision_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='hours_per_day',
            field=models.DecimalField(decimal_places=1, default=6, max_digits=4),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='period_system',
            field=models.CharField(choices=[('TRIMESTER', 'Trimestres (3)'), ('SEMESTER', 'Semestres (2)')], default='TRIMESTER', max_length=12),
        ),
    ]
