# Generated by Django 5.1.4 on 2026-06-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_add_expense_and_lessonlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='method',
            field=models.CharField(choices=[('CAISSE', 'Caisse'), ('BANQUE', 'Banque')], default='CAISSE', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CAISSE', 'Caisse'), ('BANQUE', 'Banque')], default='CAISSE', max_length=10),
        ),
    ]
