# Generated by Django 5.1.4 on 2026-06-30 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_expense_method_payment_method'),
        ('users', '0011_invitation_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.ecole'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.ecole'),
        ),
    ]
